version: '3.8'

services:
  chat:
    build: .
    container_name: chat-service
    ports:
      - "3003:3003"
    environment:
      - REDIS_HOST=redis
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - redis

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
